[package]
name = "rustdev"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = {version = "0.32.0", features = ["default"]}
reqwest = {version = "0.12.22", features = ["blocking"]}
rss = "2.0.12"
